openapi: 3.0.3
info:
  title: Example API with Style and Explode
  version: 1.0.0
servers:
- url: /
paths:
  /test:
    get:
      summary: Demonstrate query and header parameters with style/explode variations
      parameters:
      - name: foo
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: array
          items:
            type: string
      - name: bar
        in: query
        required: false
        style: spaceDelimited
        explode: false
        schema:
          type: array
          items:
            type: string
      - name: baz
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: array
          items:
            type: string
      - name: X-Foo
        in: header
        required: false
        style: simple
        explode: true
        schema:
          type: array
          items:
            type: string
      - name: X-Bar
        in: header
        required: false
        style: simple
        explode: false
        schema:
          type: array
          items:
            type: string
      - name: X-Baz
        in: header
        required: false
        style: simple
        explode: true
        schema:
          type: array
          items:
            type: string
      - name: X-FooBar
        in: header
        required: false
        style: simple
        explode: false
        schema:
          type: array
          items:
            type: string
      responses:
        "200":
          description: Success
          headers:
            foo:
              description: test
              style: simple
              explode: false
              schema:
                type: array
                items:
                  type: string
            bar:
              description: test
              style: simple
              explode: false
              schema:
                type: array
                items:
                  type: string
    post:
      summary: Demonstrate encoding with style/explode variations
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: "#/components/schemas/test_body"
            encoding:
              file:
                style: form
                explode: true
              fileWithOnlyStyle:
                style: form
              fileWithOnlyExplode:
                style: form
                explode: true
              fileWithout:
                contentType: "image/png, image/jpeg"
                style: form
      responses:
        "200":
          description: Success
components:
  schemas:
    test_body:
      type: object
      properties:
        file:
          type: string
          format: binary
        fileWithOnlyStyle:
          type: string
          format: binary
        fileWithOnlyExplode:
          type: string
          format: binary
        fileWithout:
          type: string
          format: binary
